-- ====================================================================
-- Script : Synonyms.sql
-- Goal   : Create VIEWS Synonym in Carepoint PDB (Oracle 21c)
-- ====================================================================
SET ECHO ON

GRANT SELECT, INSERT, UPDATE, DELETE ON usr_data.VW_DOCTORS TO USR_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON usr_data.VW_DOCTORS_APP TO USR_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON usr_data.VW_PATIENTS TO USR_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON usr_data.VW_PATIENTS_APP TO USR_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON usr_data.VW_INVOICES TO USR_APP;

CREATE OR REPLACE SYNONYM usr_app.DOCTORS FOR usr_data.VW_DOCTORS;
CREATE OR REPLACE SYNONYM usr_app.DOCTORS_APP FOR usr_data.VW_DOCTORS_APP;

CREATE OR REPLACE SYNONYM usr_app.PATIENTS FOR usr_data.VW_PATIENTS;
CREATE OR REPLACE SYNONYM usr_app.PATIENTS_APP FOR usr_data.VW_PATIENTS_APP;

CREATE OR REPLACE SYNONYM usr_app.INVOICES FOR usr_data.VW_INVOICES;

EXIT